[package]
name = "prop-builder"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["protosim"]

[dependencies]
protosim = { version = "^0.1.0", path = "./protosim" }
rdkafka = "0.29.0"
tokio = "1.23.0"
redis = "0.22.1"
futures = "0.3.25"
serde_json = "1.0.91"
