[package]
name = "prop-builder"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "prop-builder"
path = "src/main.rs"

[workspace]
members = ["protosim"]
exclude = ["protosim_py"]

[dependencies]
log = "0.4.17"
simplelog = "0.12.0"
time = "0.3.17"
protosim = { version = "^0.1.0", path = "./protosim" }
ethers = "^2.0.2"
rdkafka = "0.29.0"
tokio = { version = "1.23.0", features = ["full"] }
redis = { version = "0.22.1", features = ["tokio-comp"] }
futures = "0.3.25"
serde_json = { version = "1.0.91", features = ["arbitrary_precision"] }
serde = "1.0.152"
clap = { version = "4.2.7", features = ["derive"] }
reqwest = "0.11.14"

[dev-dependencies]
rstest = "0.16.0"
http = "0.2.8"

[profile.bench]
debug = true
