[package]
name = "protosim"
version = "0.1.0"
edition = "2021"


[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
ethers = "^2.0.2"
indexmap = { version = "1.7", features = ["std"] }
itertools = "0.10.5"
petgraph = "0.6.2"
enum_dispatch = "0.3.8"
serde_json = "1.0.105"
serde = "1.0.152"
tokio = { version = "1.32.0", features = ["full"] }
futures = "0.3.25"
revm = { git = "https://github.com/bluealloy/revm", rev = "00281930d90f200ac376be5778d62bed591b9c99", features = [
    "ethersdb",
] }
hex = "0.4.3"
thiserror = "1"

[dev-dependencies]
approx = "0.3.2"
rstest = "0.16.0"

[features]
default = ["network_tests"]
network_tests = []
