[package]
name = "protosim"
version = "0.1.0"
edition = "2021"


[dependencies]
log = "0.4.17"
ethers = "^2.0.2"
indexmap = { version = "1.7", features = ["std"] }
itertools = "0.10.5"
petgraph = "0.6.2"
enum_dispatch = "0.3.8"
serde = "1.0.152"
tokio = { version = "1.23.0", features = ["full"] }
futures = "0.3.25"
revm = { git = "https://github.com/bluealloy/revm", tag = "v22", features = [
    "ethersdb",
] }

[dev-dependencies]
approx = "0.3.2"
rstest = "0.16.0"


[profile.bench]
debug = true
