[package]
name = "protosim"
version = "0.1.0"
edition = "2021"


[dependencies]
log = "0.4.17"
ethers = "1.0.1"
indexmap = { version = "1.7", features = ["std"] }
itertools = "0.10.5"
petgraph = "0.6.2"
enum_dispatch = "0.3.8"


[dev-dependencies]
approx = "0.3.2"
rstest = "0.16.0"
