name: Continuous Integration

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  tests-and-lints:
    uses: ./.github/workflows/tests-and-lints-template.yaml
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      infura_api_key: ${{ secrets.INFURA_API_KEY }}
