name: Release Python Wheel

on:
  pull_request

permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  protosim_py_release:
    name: Protosim-Py Build Wheel
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/build-push-action@v2
        with:
          tags: protosim-py-build:latest
          file: protosim_py/protosim_py.Dockerfile
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: protosim-py-build:latest
          options: -v ${{ github.workspace }}:/prop-builder
          run: |
            /opt/python/cp39-cp39/bin/python -m maturin build --release --compatibility manylinux2014 -i /opt/python/cp39-cp39/bin/python
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: protosim-py
          path: |
            ./protosim_py/target/wheels/*.whl
